### ISSUE TITLE
Standardize output format

### ISSUE THREAD

**Issue by fulldecent** [mcandre/aspelllint#16]
Hello, would this project be interested in a PR that make output follow a standardized format, namely https://github.com/fulldecent/structured-acceptance-test ?

**Comment by mcandre** [comment]
sounds cool, sure!

**Comment by mcandre** [comment]
if you'd like, i have a few other linters as well that could use some love:

https://rubygems.org/profiles/mcandre

**Comment by fulldecent** [comment]
You got it.

I am new in this space, could you please provide idiot proof instructions for building, testing, and running this software from Git?

**Comment by mcandre** [comment]
No problem!

```
$ git clone git@github.com:mcandre/aspelllint.git
```

(Or your GitHub fork's clone URL)

Then:

```
$ cd aspelllint/
$ gem install bundler
$ bundle install
$ rake test
```

**Comment by ilyalyo** [comment]
Added a PR: https://github.com/mcandre/aspelllint/pull/17

**Comment by mcandre** [comment]
merged
